version: '3.8'
services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PG_DATABASE=notesdb
      - PG_USER=postgres
      - PG_PASSWORD=your_password
      - PG_HOST=postgres
      - JWT_SECRET=RahasiaSuperAmanAnda
    depends_on:
      - postgres
  
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: notesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: